### ISSUE TITLE
change m.Migrate by m.Up

### ISSUE THREAD

**Issue by mfuentesg** [sebnyberg/sqlite-migrate-example#1]
Hey!

Thanks for this repo, it was very useful for a personal project that I'm working on.
Just a suggestion, using `m.Migrate` is forcing to know what is the name of the revision that you want to apply.

https://github.com/sebnyberg/sqlite-migrate-example/blob/d17e27353653750fb5d5ea9b7a5d6c86130327ee/main.go#L41

In my case I wanted to apply multiple migrations, so, instead to use `m.Migrate` I used `m.Up` which applies all the existing migrations.

**Comment by sebnyberg** [comment]
Hey, thanks for the comment.

I think it comes down to personal preference. I prefer explicitly stating the version over automatically migrating to the latest one. It gives some extra flexibility at the cost of having to remember to bump the version.

**Comment by sebnyberg** [comment]
Note that the only possible downside to explicitly stating the version is that you may forget to bump it. This is easily fixed and just takes some getting used to.
